version: "3.9"

services:
  nextjs:
    container_name: house_kari_app
    build:
      context: .
      dockerfile: Dockerfile
    image: house_kari:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
